contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

 #contact CRUD
    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    path('contact/create/', views.create, name='create'),

 #user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
#DOC dos campos https://docs.djangoproject.com/pt-br/4.2/ref/models/fields/#field-choices

#nao esquecer de criar a migracao comando; python manage.py makemigrations
#nao esquecer de aplicar a migracao para ir pro BD; python manage.py migrate

class Category(models.Model):
    #tira o plural e muda o nome de exibicao se necessario dos models
    #_() para indicar traducao
    class Meta:
        verbose_name = 'Categoria'

    name = models.CharField(max_length=30)
        
    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    class Meta:
        verbose_name = 'Contato'
    #campos obrigatorios / para nao ser obrigadorio acrescentar; blank=True no parametro
    first_name = models.CharField(max_length=12)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=11)
    email = models.EmailField(max_length=30, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField (default=True)
    picture = models.ImageField(upload_to='pictures/%Y/%m', blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    #criar usuario
    owner= models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

#colocando nome de exibicao dos contatos criados na lista a ser exibida
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
            'accept': 'image/*',
            }
        )
    )

    class Meta:
        model = models.Contact
        fields = ('first_name','last_name', 'phone', 'email', 'description', 'category', 'picture',)
        # widget=forms.TextInput(
        #     attrs={
        #         'class': 'classe-a classe b',
        #         'placeholder': 'Aqui veio do init',
        #     }
        # )
    
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name =cleaned_data.get('first_name')
        last_name =cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError('Segundo nome nao pode ser igual ao primeiro', code='invalid')
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        #self.add_error('first_name', ValidationError('Mensagem do erro', code='invalid'))

        return super().clean()
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
            'first_name', ValidationError('retorn o valor do campo aqui', code='invalid'))
        print('TESTE')
        
        return first_name
    
class RegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    lasT_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password1','password2',
        )
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error('email',
                           ValidationError('Ja existe esse email', code='invalid'))

        return email

contact/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(
        request,
        'contact/index.html',
    )

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact

# Create your views here.
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
            form = ContactForm(request.POST, request.FILES)

            context = {
                'form': form,
                'form_action':form_action,
            }
            if form.is_valid():
                contact = form.save()
                return redirect('contact:update', contact_id=contact.pk)

            return render(
                request,
                'contact/create.html',
                context
            )

    context = {
        'form': ContactForm(),
        'form_action':form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )

def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)

    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
            form = ContactForm(request.POST,  request.FILES, instance=contact)

            context = {
                'form': form,
                'form_action':form_action,
            }
            if form.is_valid():
                  contact = form.save()
                  return redirect('contact:update', contact_id=contact.pk )

            return render(
                request,
                'contact/create.html',
                context
            )

    context = {
        'form': ContactForm(instance=contact),
        'form_action':form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )
def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    confirmation = request.POST.get('confirmation', 'no')
    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')
    
    return render(request, 'contact/contact.html',
                  {
                       'contact':contact,
                       'confirmation':confirmation,
                  })

contact/views/contact_views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    #paginacao django
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title':  'Contatos - '
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    # Q eh um model do django para trocar a consulta AND por OR envolver em parenteses
    #precisa fazer o importe do model antes.

    contacts = Contact.objects.filter(show=True) \
        .filter(
            Q(first_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value) |
            Q(last_name__icontains=search_value)
            )\
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title':  'Search - ',
        'search_value': search_value,
    }

    return render(
        request,
        'contact/index.html',
        context
    )

def contact(request, contact_id):
    #metodo get pega um/ pk= primary key
    single_contact = get_object_or_404(Contact.objects, pk=contact_id, show=True)

    site_title = f'{single_contact.first_name}{single_contact.last_name} -'

    context = {
        'contact': single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth, messages

def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario registrado')
            return redirect('contact:index')

    return render(        
        request, 
        'contact/register.html',
        {
            'form':form
        }
    )

def login_view(request):
        form = AuthenticationForm(request)

        if request.method == 'POST':
             form = AuthenticationForm(request, data=request.POST)
             if form.is_valid():
                  user = form.get_user()
                  auth.login(request, user)
                  messages.success(request, 'logado com sucesso')
                  return redirect('contact:index')
        messages.error(request, 'login invalido' )
        
        return render(        
            request, 
            'contact/login.html',
            {
                'form':form
            }
        )

def logout_view(request):
     auth.logout(request)
     return redirect('contact:login')

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>
        <p><b>ID:</b> {{ contact.id }}<p/>
        <p><b>e_mail:</b> {{ contact.email }}<p/>
        <p><b>Phone:</b> {{ contact.phone }}<p/>
        <p><b>Created Date:</b> {{ contact.created_date }}<p/>
        <p><b>Description:</b> {{ contact.description }}<p/>
        <p><b>Category:</b> {{ contact.category.name }}<p/>
            {% if contact.picture %}
        <p><img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}"></p>
            {% endif %}
        <div class="contact-links">
            <a class="btn btn-link" href="{% url "contact:update" contact.id %}">Update</a>

            <form action="{% url "contact:delete" contact.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                <input type="hidden" name="confirmation" value="yes">
                <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
                {% else %}
                <button class="btn btn-link btn-delete" type="submit">Delete</button>
                {% endif %}
                
            </form>
        </div>

    </div>

{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}
{% block content %}
    <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="/contact/create/"
      method="POST"
      enctype="multipart/form-data"
    >
    {% csrf_token %}

      <div class="form-content">
        {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>

        {% if field.name == 'picture' and field.value.url  %}
        <div class="form-group">
          <img src="{{ field.value.url }}" alt="">
        </div>
        {% endif %}

        {% endfor %}
      </div>

      {% if form.non_field_errors %}
      <div class="form-content">
        <div class="form-group">
          <div class="message error">
            {{ form.non_field_errors }}
          </div>
        </div>
      </div>
      {% endif %}
      
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>

{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}
{% block content %}

{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-header">
                    <th class= "table-header">Id</th>
                    <th class= "table-header">Fist name</th>
                    <th class= "table-header">Last name</th>
                    <th class= "table-header">Phone</th>
                </tr>  
            </thead>
            <tbody>
                {% for contact in page_obj %}
                    <tr class="table-row">
                        <td class="table-cell">
                            <a class="table-link" href="{% url "contact:contact" contact.id %}">{{contact.id}}</a>
                        </td>
                        <td class="table-cell">
                            {{contact.first_name}}
                        </td>
                        <td class="table-cell">
                            {{contact.last_name}}
                        </td>
                        <td class="table-cell">
                            {{contact.phone}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nenhum contato encontrado
    </h1>
</div>
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}
{% block content %}
  <div class="form-wrapper">
    <h2> Login {{ user }} </h2>

    {% if user.is_authenticated %}
    <p>voce fez login como {{ user.username }}</p>
    Clique <a href="{% url "contact:logout" %}">aqui</a>
    para sair
    {% else %}
    {% include "contact/partials/user-form.html" %}
    {% endif %}
  </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}
{% block content %}
  <div class="form-wrapper">
    <h2> Register</h2>
    {% include "contact/partials/user-form.html" %}
  </div>
{% endblock content %}